### ISSUE TITLE
Azure Repos on the roadmap?

### ISSUE THREAD

**Issue by camara-raf** [gitoqlik/helpdesk#4]
I'm very eager to start using gitoqlik with my team, and finally be able to introduce an easy way to do code versioning in Qlik.

Knowing that in my work we're a Microsoft shop, I'm not sure if I would be able to use github since Azure Repos is already available.

Are there any plans to have Azure Repos as a supported repository?

Regardless or Repos support or not, this is a great additional and I'm looking forward to see every new feature on this amazing solution. Thank you.

**Comment by shatzibitten** [comment]
You are the second user that asks about Azure Repos. 
We have that provider in our roadmap, but we have limited resources now, so that's why there is no deadline for that feature. 
I think this year we will get it

**Comment by shatzibitten** [comment]
https://github.com/orgs/gitoqlik/projects/1#card-44250937

**Comment by shatzibitten** [comment]
@camara-raf done =) Azure successfully released!
