### ISSUE TITLE
Azure DevOps - Can't connect to repo/Can't deploy exiting app

### ISSUE THREAD

**Issue by camara-raf** [gitoqlik/helpdesk#5]
Using Azure DevOps repository, if the appid does not match with the main id of a repo, when trying to ‘connect to existing repository as branch’, no repository shows up.
 
![image](https://user-images.githubusercontent.com/31748282/93634837-43377880-f9bf-11ea-981f-094a0a4bfcf4.png)

The same behavior can be found when trying to ‘Deploy app’ from the hub:

![image](https://user-images.githubusercontent.com/31748282/93634844-47639600-f9bf-11ea-879f-3f5419dd476a.png)

Log files can be found here: https://1drv.ms/u/s!AtltkX-ckkINg-kvWHrzN9DloVTwTg?e=Jb159b

**Comment by camara-raf** [comment]
Test done on Qlik Sense Enterprise environment.

**Comment by shatzibitten** [comment]
@camara-raf fixed
