### ISSUE TITLE
Github - App Thumbnail image updated to app doesn't get saved.

### ISSUE THREAD

**Issue by camara-raf** [gitoqlik/helpdesk#6]
An app thumbnail that is uploaded to the doesn't go to the repository; Image is in the 'app content'. 
When deploying the app in another environment (DEV to UAT), thumbnail is broken.

**Dev**:
![image](https://user-images.githubusercontent.com/31748282/93636495-0ae56980-f9c2-11ea-9927-7dce69bc49b3.png)

**Main Branch Repository : objects/properties.josn**
![image](https://user-images.githubusercontent.com/31748282/93636623-4122e900-f9c2-11ea-8a3d-69d46006dfb0.png)

**UAT**
![image](https://user-images.githubusercontent.com/31748282/93636810-8b0bcf00-f9c2-11ea-811a-1fbbdef1e04b.png)

![image](https://user-images.githubusercontent.com/31748282/93637070-f8b7fb00-f9c2-11ea-9c17-9936de32938a.png)

**Testing Branch Repository: objects/properties.json** [App id in the qURL didn't change even after deploying in a new environment, that creates a new id]
![image](https://user-images.githubusercontent.com/31748282/93636916-ba224080-f9c2-11ea-8e54-620bc16ee53a.png)

Environment: Qlik Sense Enterprise on Windows

Is the App content out not being imported by design?

**Comment by camara-raf** [comment]
Log file from deployment can be found: Log files can be found here: https://1drv.ms/u/s!AtltkX-ckkINg-kvWHrzN9DloVTwTg?e=Jb159b  (gitoqlik_log_18-9-2020_3-30-37_gitHub_DeployThumbnailIssue.txt)

**Comment by shatzibitten** [comment]
@camara-raf thanks! it is known issue, static content doesn't imported by design. But we are going to store thumbnails in the repository because of their small size. 
I will update that issue

**Comment by shatzibitten** [comment]
@camara-raf done in 1.5.4 version. Please check it
