### ISSUE TITLE
Azure DevOps - Deploy Existing App Issue - Sheets are not created / Gitoqlik options not visible / Autogenerated section Missing

### ISSUE THREAD

**Issue by camara-raf** [gitoqlik/helpdesk#7]
Environment: Qlik Sense Enterprise November 2019
Gitoqlik version: 1.5.4
Actions: 
1) Repository created from a development environment successfully (committed with load script and app objects)
![image](https://user-images.githubusercontent.com/31748282/95882220-6d265580-0d47-11eb-89fd-458911eaf9c0.png)

2) Deploy the app in a QA environment; App created successfully
![image](https://user-images.githubusercontent.com/31748282/95882276-7f07f880-0d47-11eb-8f90-eae82d3d19ba.png)

3) Opening the App, sheets are not created; Auto-Generated load script section not created
![image](https://user-images.githubusercontent.com/31748282/95882301-86c79d00-0d47-11eb-8f49-4176c0ec671d.png)
![image](https://user-images.githubusercontent.com/31748282/95882885-38ff6480-0d48-11eb-90ce-9c330f789ea4.png)

4) Accessed Gitoqlik to try to import sheets, but options are not available
![image](https://user-images.githubusercontent.com/31748282/95882985-56343300-0d48-11eb-9b06-905b340e87a3.png)

5) Auto Generated script not created in the repository, but listed in the tab_order.txt
![image](https://user-images.githubusercontent.com/31748282/95882722-07869900-0d48-11eb-8b85-67da66ddfa24.png)

**Comment by RomanYamp** [comment]
Have you tried to refresh the application? I believe sheets will appear once you do the refresh

**Comment by camara-raf** [comment]
You're right, I see the sheets after the data refresh. Apologies for that.
But issues from step 4) and 5) are still there, even after a data refresh.

**Comment by RomanYamp** [comment]
About 4, gitoqlik has different functions in script editor mode and sheet viewer mode. Just check the import sheet function while viewing one of your sheets, not the script

**Comment by RomanYamp** [comment]
And 5: Maybe developers will correct me, but the auto-generated tab is not the one that ment to be serialized. This tab is used to view current version of app inside of the current environment. Even your screen with taborder.txt shows that autogenerated.qvs file is not serialized.

**Comment by camara-raf** [comment]
Same result of both modes:
![image](https://user-images.githubusercontent.com/31748282/95888605-49ffa400-0d4f-11eb-870b-ec6add159e18.png)


I noticed this behavior in another app in the same environment (QA), but that is not consistent, I see the options while in the App Overview mode. 

5) So the autogenerated.qvs (script created when data is imported using the Data Manager) isn't serialized?  Does it mean that we can't serialize and version control scripts that were created using the Data Manager?

**Comment by RomanYamp** [comment]
About 5 my bad. I considered this one like created by gitoqlik. @shatzibitten think it's better to leave answers about 4 and 5 for You

**Comment by shatzibitten** [comment]
The current version doesn't support autogenerated script. 

But the 4th is a very strange behavior.  Please attach log file

**Comment by shatzibitten** [comment]
@camara-raf please attach log file with issue (the 4th point)

**Comment by shatzibitten** [comment]
@camara-raf we have fixed, please check it. 
Now we are serializing load script

**Comment by camara-raf** [comment]
Thank you @shatzibitten , I confirm that I can see the Autogenerated script in the repository, and I can update the script successfully when I'm in the load script section. But when I'm at the app overview and chose to update the app (objects and script), the auto-generated section doesn't show up. This section does not gets created when I deploy the app for the first time.

Regarding 4), I can't replicate it. If I stumble on it again I'll capture the logs and post it again.

**Comment by camara-raf** [comment]
I'm closing this issue as I reported many things together and most of it was addressed. I still see that the Auto-Generated script doesn't appear all the time in an app that is deployed, but If needed I'll open a separate 'ticket'.
Thanks.
